"use client";

import React, { useState, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  ArrowRight,
  Globe,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  FileText,
  Code2,
  Bot,
  Map,
  Share2,
  ShieldCheck,
  Heading1,
  Download,
  Clock,
  Link2,
} from "lucide-react";
import { cn } from "@/utils/cn";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useLanguage } from "@/components/LanguageContext";

/* ────────────────────────────────────────────────
   Page de résultat partagé (lien temporaire 1h)
   ──────────────────────────────────────────────── */

interface ScanCheck {
  id: string;
  label: string;
  status: "pass" | "warn" | "fail";
  detail: string;
  points: number;
  maxPoints: number;
}

interface ScanResult {
  domain: string;
  score: number;
  maxScore: number;
  verdict: "critical" | "warning" | "good";
  checks: ScanCheck[];
  scannedAt: string;
}

const content = {
  fr: {
    loading: "Chargement du diagnostic...",
    expired: "Ce lien a expire ou n'existe plus.",
    expiredSub: "Les liens de partage sont valides 1 heure. Lancez un nouveau scan.",
    newScan: "Nouveau scan",
    scoreLabel: "Score de visibilité IA",
    checksTitle: "Detail du diagnostic",
    sharedReport: "Rapport partage",
    expiresIn: "Expire dans",
    minutes: "min",
    exportPdf: "Exporter PDF",
    ctaTitle: "Améliorez votre visibilité IA",
    ctaBody: "Ce diagnostic a été généré par Aissa Belkoussa. Réservez un appel stratégique gratuit pour passer de invisible à recommandé.",
    ctaButton: "Réserver un appel",
    ctaFree: "Gratuit — 30 minutes — Sans engagement",
    verdicts: {
      critical: { label: "Critique", desc: "Les IA ne connaissent pas cette entreprise." },
      warning: { label: "Insuffisant", desc: "Quelques signaux existent, mais les IA preferent les concurrents." },
      good: { label: "Bon niveau", desc: "Le site envoie les bons signaux. Quelques optimisations restent possibles." },
    },
    googleVsAi: {
      google: "~2% de conversion",
      googleSub: "Google donne des options",
      ai: "~15%+ de conversion",
      aiSub: "L'IA donne une reponse",
    },
  },
  en: {
    loading: "Loading diagnostic...",
    expired: "This link has expired or no longer exists.",
    expiredSub: "Share links are valid for 1 hour. Run a new scan.",
    newScan: "New scan",
    scoreLabel: "AI Visibility Score",
    checksTitle: "Diagnostic breakdown",
    sharedReport: "Shared report",
    expiresIn: "Expires in",
    minutes: "min",
    exportPdf: "Export PDF",
    ctaTitle: "Improve your AI visibility",
    ctaBody: "This diagnostic was generated by Aissa Belkoussa. Book a free strategy call to go from invisible to recommended.",
    ctaButton: "Book a call",
    ctaFree: "Free — 30 minutes — No strings attached",
    verdicts: {
      critical: { label: "Critical", desc: "AI doesn't know this business." },
      warning: { label: "Insufficient", desc: "Some signals exist, but AI prefers competitors." },
      good: { label: "Good", desc: "The site sends the right signals. A few optimizations remain." },
    },
    googleVsAi: {
      google: "~2% conversion",
      googleSub: "Google gives options",
      ai: "~15%+ conversion",
      aiSub: "AI gives an answer",
    },
  },
};

const CHECK_ICONS: Record<string, React.ElementType> = {
  homepage: Globe,
  "meta-description": FileText,
  title: Heading1,
  schema: Code2,
  h1: Heading1,
  robots: Bot,
  sitemap: Map,
  "llms-txt": Bot,
  "og-tags": Share2,
};

const VERDICT_CONFIG = {
  critical: { icon: XCircle, color: "text-red-500", bg: "bg-red-50 border-red-200" },
  warning: { icon: AlertTriangle, color: "text-amber-500", bg: "bg-amber-50 border-amber-200" },
  good: { icon: CheckCircle2, color: "text-emerald-500", bg: "bg-emerald-50 border-emerald-200" },
};

const STATUS_ICON = {
  pass: { icon: CheckCircle2, color: "text-emerald-500" },
  warn: { icon: AlertTriangle, color: "text-amber-500" },
  fail: { icon: XCircle, color: "text-red-400" },
};

export default function SharedResultPage() {
  const { id } = useParams<{ id: string }>();
  const { language } = useLanguage();
  const t = content[language] || content.fr;

  const [result, setResult] = useState<ScanResult | null>(null);
  const [expiresAt, setExpiresAt] = useState<number | null>(null);
  const [expired, setExpired] = useState(false);
  const [loading, setLoading] = useState(true);
  const [remaining, setRemaining] = useState("");

  useEffect(() => {
    if (!id) return;
    fetch(`/api/scan/share?id=${id}`)
      .then((res) => {
        if (!res.ok) throw new Error("expired");
        return res.json();
      })
      .then(({ data, expiresAt: exp }) => {
        setResult(data);
        setExpiresAt(exp);
        setLoading(false);
      })
      .catch(() => {
        setExpired(true);
        setLoading(false);
      });
  }, [id]);

  // Countdown timer
  useEffect(() => {
    if (!expiresAt) return;
    const tick = () => {
      const diff = expiresAt - Date.now();
      if (diff <= 0) {
        setExpired(true);
        setRemaining("0");
        return;
      }
      setRemaining(String(Math.ceil(diff / 60000)));
    };
    tick();
    const interval = setInterval(tick, 30000);
    return () => clearInterval(interval);
  }, [expiresAt]);

  const exportPdf = useCallback(() => {
    window.print();
  }, []);

  if (loading) {
    return (
      <div className="bg-site-bg min-h-screen">
        <Header />
        <main className="pt-40 pb-20 px-[var(--spacing-container)]">
          <div className="max-w-3xl mx-auto text-center">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 1.2, repeat: Infinity, ease: "linear" }}
              className="w-8 h-8 border-2 border-site-text border-t-transparent rounded-full mx-auto mb-4"
            />
            <p className="text-sm text-site-text-light">{t.loading}</p>
          </div>
        </main>
      </div>
    );
  }

  if (expired || !result) {
    return (
      <div className="bg-site-bg min-h-screen">
        <Header />
        <main className="pt-40 pb-20 px-[var(--spacing-container)]">
          <div className="max-w-xl mx-auto text-center">
            <Clock size={48} className="text-site-text-light/20 mx-auto mb-6" />
            <h1 className="text-2xl md:text-3xl font-medium tracking-tighter mb-4">{t.expired}</h1>
            <p className="text-site-text-light mb-8">{t.expiredSub}</p>
            <Link
              href="/scan"
              className="inline-flex items-center gap-3 bg-site-text text-site-bg px-8 py-4 rounded-full text-xs font-bold uppercase tracking-[0.15em] hover:scale-[1.02] active:scale-[0.98] transition-all"
            >
              {t.newScan}
              <ArrowRight size={14} />
            </Link>
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  const v = VERDICT_CONFIG[result.verdict];
  const VIcon = v.icon;
  const verdictText = t.verdicts[result.verdict];

  return (
    <div className="bg-site-bg min-h-screen">
      <Header />

      <main className="pt-32 md:pt-40 pb-20 px-[var(--spacing-container)]">
        <div className="max-w-3xl mx-auto" id="scan-report">
          {/* Header bar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-12 print:mb-8">
            <div className="flex items-center gap-3">
              <Link2 size={14} className="text-site-text-light/30" />
              <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-site-text-light/40">
                {t.sharedReport}
              </span>
              {remaining && !expired && (
                <span className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[0.15em] text-amber-500">
                  <Clock size={10} />
                  {t.expiresIn} {remaining} {t.minutes}
                </span>
              )}
            </div>
            <button
              onClick={exportPdf}
              className="inline-flex items-center gap-2 px-4 py-2 border border-site-border rounded-lg text-xs font-bold uppercase tracking-[0.15em] text-site-text-light hover:border-site-text hover:text-site-text transition-colors print:hidden"
            >
              <Download size={12} />
              {t.exportPdf}
            </button>
          </div>

          {/* Domain + Score */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-16"
          >
            {/* Domain */}
            <div className="flex items-center gap-3 mb-8">
              <div className="w-10 h-10 rounded-full bg-site-text text-site-bg flex items-center justify-center text-sm font-bold uppercase">
                {result.domain[0]}
              </div>
              <div>
                <p className="text-lg font-medium">{result.domain}</p>
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-site-text-light/40">
                  {new Date(result.scannedAt).toLocaleDateString(language === "fr" ? "fr-FR" : "en-US", {
                    day: "numeric",
                    month: "long",
                    year: "numeric",
                  })}
                </p>
              </div>
            </div>

            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-site-text-light/40 mb-6">
              {t.scoreLabel}
            </p>

            <div className="flex items-end gap-3 mb-4">
              <span className={cn("text-8xl md:text-[120px] font-medium tracking-tighter leading-none", v.color)}>
                {result.score}
              </span>
              <span className="text-3xl md:text-4xl text-site-text-light/20 tracking-tighter font-light mb-2">
                / {result.maxScore}
              </span>
            </div>

            <div className="flex flex-col sm:flex-row sm:items-center gap-3">
              <div className={cn("inline-flex items-center gap-2 px-4 py-2 rounded-full border text-xs font-bold uppercase tracking-[0.15em] w-fit", v.bg)}>
                <VIcon size={14} className={v.color} />
                <span className={v.color}>{verdictText.label}</span>
              </div>
              <p className="text-sm text-site-text-light">{verdictText.desc}</p>
            </div>
          </motion.div>

          {/* Checks */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mb-16"
          >
            <h2 className="text-[10px] font-bold uppercase tracking-[0.2em] text-site-text-light/40 mb-6">
              {t.checksTitle}
            </h2>

            <div className="border border-site-border rounded-2xl overflow-hidden divide-y divide-site-border">
              {result.checks.map((check, i) => {
                const s = STATUS_ICON[check.status];
                const SIcon = s.icon;
                const CIcon = CHECK_ICONS[check.id] ?? ShieldCheck;
                return (
                  <motion.div
                    key={check.id}
                    initial={{ opacity: 0, x: -8 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.25 + i * 0.05 }}
                    className="flex items-start gap-4 p-5 md:p-6"
                  >
                    <CIcon size={18} className="text-site-text-light/25 mt-0.5 shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-3 mb-1">
                        <span className="text-sm font-medium">{check.label}</span>
                        <div className="flex items-center gap-2 shrink-0">
                          <span className="text-xs text-site-text-light/40 tabular-nums">
                            {check.points}/{check.maxPoints}
                          </span>
                          <SIcon size={14} className={s.color} />
                        </div>
                      </div>
                      <p className="text-xs text-site-text-light/60">{check.detail}</p>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </motion.div>

          {/* Google vs AI */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="grid grid-cols-2 gap-px bg-site-border rounded-2xl overflow-hidden mb-16 print:break-inside-avoid"
          >
            <div className="bg-site-bg p-8 text-center">
              <p className="text-2xl md:text-3xl font-medium tracking-tighter text-site-text-light/25">
                {t.googleVsAi.google}
              </p>
              <p className="text-[10px] font-bold uppercase tracking-[0.15em] text-site-text-light/40 mt-2">
                {t.googleVsAi.googleSub}
              </p>
            </div>
            <div className="bg-site-bg p-8 text-center">
              <p className="text-2xl md:text-3xl font-medium tracking-tighter">
                {t.googleVsAi.ai}
              </p>
              <p className="text-[10px] font-bold uppercase tracking-[0.15em] text-site-text-light/40 mt-2">
                {t.googleVsAi.aiSub}
              </p>
            </div>
          </motion.div>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="border border-site-border rounded-2xl p-8 md:p-12 print:break-inside-avoid"
          >
            <h3 className="text-2xl md:text-3xl font-medium tracking-tighter leading-tight mb-4">
              {t.ctaTitle}
            </h3>
            <p className="text-site-text-light leading-relaxed mb-8 max-w-[55ch]">
              {t.ctaBody}
            </p>
            <Link
              href="/contact?plan=accelerateur"
              className="inline-flex items-center gap-3 bg-site-text text-site-bg px-8 py-4 rounded-full text-xs font-bold uppercase tracking-[0.15em] hover:scale-[1.02] active:scale-[0.98] transition-all print:hidden"
            >
              {t.ctaButton}
              <ArrowRight size={14} />
            </Link>
            <p className="text-[11px] text-site-text-light/40 mt-4 print:hidden">{t.ctaFree}</p>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
